{% set name = "langchain-google-genai" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_google_genai-{{ version }}.tar.gz
  sha256: aa0dd7807a9a15651d10cd228c574f23fe46e2ce62921bf21d73a63869ecd814

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=1.2.2,<2.0.0
    - google-genai >=1.56.0,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - filetype >=1.2.0,<2.0.0

test:
  imports:
    - langchain_google_genai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain-google
  summary: An integration package connecting Google's genai package and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
